### ISSUE TITLE
[Intro to iOS] Prework - Review my app

### ISSUE THREAD

**Issue by avo1** [avo1/TipCalc#1]
Hi Mr. Sang, my app is completed. Please review /cc @chug2k

**Comment by chug2k** [comment]
:+1:  Excellent job with the Tip Calculator! Congratulations, you're accepted to the class - see you on November 9th! We will email you at your gmail.com email address soon with information about exactly where to meet. 

### Quick Comments:
- :open_mouth: Good job with AutoLayout. We won't learn about AutoLayout until the second week of class, but it looks like you have a good understanding already. You have a few AutoLayout warnings but we'll learn more about how to fix those in Week 2. 
- I love the smiley. :laughing: 
- Good usage of `NSUserDefaults`. Your approach with `SETTING_STRING` to combine multiple values is interesting, but a bit complicated. An easier, more standard approach is to store a `Dictionary` to `NSUserDefaults`. Example from Stack Overflow here: http://stackoverflow.com/a/25753088/396324.
- It’s true that `valueChanged` is not triggered “by code”. The reason is because `valueChanged` is a UIKit event. In later weeks we’ll talk about ways to “observe” values from code, but what you did is generally easiest - just call the appropriate function. 
- Good job using `NSNumberFormatter` and `NSLocale`.
- Great usage of the `UITextFieldDelegate` with the `shouldChangeCharactersInRange` function. Delegates are how we listen to events. We'll learn more about those too!

### Small code comments
- `if roundedTipLabel.hidden == false` can be written as `if !roundedTipLabel.hidden`. 
- One small comment, related to code organization, is that using `roundedTipLabel.hidden` to store information is a little messy. It is better to keep the state of your UI separate from your logic, but I understand why you took this shortcut. 

### Optional Suggestions to Improve

Look into the `UIView.animateWithDuration` functions to add animations.

/cc @marcusellison @harley @minhchau273

**Comment by avo1** [comment]
@chug2k , thanks for the good news and your very detail code review. I've cleaned up my code, change to use Dictionary, remove the shortcut. I also fix a bug where user copy some text and paste to the bill text box, by disabling paste function :smile: 
See you next week.

**Comment by chug2k** [comment]
:100: Great edits!!
